#!/usr/bin/env python
import os
from flask import Flask


instancepath = os.path.join(os.environ['OPENSHIFT_PYTHON_DIR'], 'instance')
app = application = Flask(__name__, instance_path=instancepath)


# The '/' page is accessible to anyone
@app.route('/')
def home():
    return "Hello world!"


#
# Main, for testing
#
if __name__ == '__main__':
    ip = os.environ['OPENSHIFT_PYTHON_IP']
    port = int(os.environ['OPENSHIFT_PYTHON_PORT'])

    app.run(host=ip, port=port)
