#!/usr/bin/env python
import os
from routes import app as application

#
# Main, for testing
#
if __name__ == '__main__':
    ip = os.environ['OPENSHIFT_PYTHON_IP']
    port = int(os.environ['OPENSHIFT_PYTHON_PORT'])

    application.run(host=ip, port=port)
